language: python

python:
 - "3.4"

install:
 - pip install .

script:
 - python -m unittest discover -v -s tests

notifications:
  email:
    recipients:
      - travis@michelblancard.fr
    on_success: change
    on_failure: always
